FROM elixir:latest

ARG SET_MIX_ENV=prod
ENV MIX_ENV $SET_MIX_ENV
ARG DATABASE_URL=""
ENV DATABASE_URL=$DATABASE_URL
ARG KATA_DISCORD_TOKEN
ENV KATA_DISCORD_TOKEN $KATA_DISCORD_TOKEN
WORKDIR /app

COPY . /app
COPY entrypoint.sh /app
RUN rm -rf _build 

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix deps.get

# Compile the project
RUN mix compile
RUN mix release 


CMD ["sh", "-c", "/app/entrypoint.sh ${MIX_ENV}"]
