# fly.toml app configuration file generated for kata-bot on 2023-10-26T21:33:59-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kata-bot"
primary_region = "dfw"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["https://cnb-shim.herokuapp.com/v1/hashnuke/elixir"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
